import { test, expect } from '@playwright/test';

test.describe('Quiz Lobby and Game Flow', () => {
    test('should create a room, allow joining, and start the game', async ({ page, context }) => {
        // 1. Host creates a room
        await page.goto('/');

        // Set user name via localStorage
        await page.evaluate(() => {
            localStorage.setItem('quiz_user_name', 'QuizHost');
        });

        // Reload to apply username
        await page.goto('/');

        // Navigate to Quiz
        await page.click('text=Quiz de Velocidade');

        // Create room
        await page.click('text=CRIAR NOVA SALA');

        // Wait for Lobby view to appear
        await expect(page.locator('text=SALA QUIZ')).toBeVisible();
        await expect(page.locator('text=INICIAR JOGO AGORA')).toBeVisible();

        // Extract the Room ID generated by the UI
        const roomIdText = await page.locator('h3').first().textContent();
        const roomId = roomIdText?.trim() || '';
        expect(roomId).toBeTruthy();

        // 2. Guest joins the room in a separate context
        const guestContext = await context.browser()!.newContext();
        const guestPage = await guestContext.newPage();

        await guestPage.goto('/');
        await guestPage.evaluate(() => {
            localStorage.setItem('quiz_user_name', 'QuizGuest');
        });
        await guestPage.goto('/');

        await guestPage.click('text=Quiz de Velocidade');

        // Enter the room code
        await guestPage.fill('input[placeholder="CÓDIGO DA SALA"]', roomId);
        await guestPage.click('button:has-text("ENTRAR")');

        // Guest should see the waiting lobby (no start button)
        await expect(guestPage.locator('text=Aguardando o host iniciar a partida...')).toBeVisible();

        // Host should see Guest in the lobby
        await expect(page.locator(`text=QuizGuest`)).toBeVisible();

        // 3. Host starts the game
        await page.click('text=INICIAR JOGO AGORA');

        // Both should transition to the first question
        await expect(page.locator('text=Questão 1 de')).toBeVisible({ timeout: 10000 });
        await expect(guestPage.locator('text=Questão 1 de')).toBeVisible({ timeout: 10000 });
    });
});
