import { test, expect } from '@playwright/test';

test.describe('Roletrando Lobby and Game Flow', () => {
    test('should create a room, allow joining, and start the game', async ({ page, context }) => {
        // 1. Host creates a room
        await page.goto('/');

        // Set user name via localStorage (context) since we have a UserContext checking it
        await page.evaluate(() => {
            localStorage.setItem('quiz_user_name', 'HostPlayer');
        });

        // Reload to apply username
        await page.goto('/');

        // Navigate to Roletrando
        await page.click('text=Roletrando');

        // Create room
        await page.click('text=CRIAR NOVA SALA');

        // Wait for Lobby view to appear
        await expect(page.locator('text=SALA').first()).toBeVisible();
        await expect(page.locator('text=INICIAR JOGO AGORA')).toBeVisible();

        // Extract the Room ID generated by the UI
        const roomIdText = await page.locator('h3').filter({ hasText: /^[A-Z0-9]{4}$/ }).textContent();
        const roomId = roomIdText?.trim() || '';
        expect(roomId).toBeTruthy();

        // 2. Guest joins the room in a separate context
        const guestContext = await context.browser()!.newContext();
        const guestPage = await guestContext.newPage();

        await guestPage.goto('/');
        await guestPage.evaluate(() => {
            localStorage.setItem('quiz_user_name', 'GuestPlayer');
        });
        await guestPage.goto('/');

        await guestPage.click('text=Roletrando');

        // Enter the room code
        await guestPage.fill('input[placeholder="CÓDIGO DA SALA"]', roomId);
        await guestPage.click('button:has-text("ENTRAR")');

        // Guest should see the waiting lobby (no start button)
        await expect(guestPage.locator('text=Aguardando o host iniciar a partida...')).toBeVisible();

        // Host should see Guest in the lobby
        await expect(page.locator(`text=GuestPlayer`)).toBeVisible();

        // 3. Host starts the game
        await page.click('text=INICIAR JOGO AGORA');

        // Both should transition to the game board
        // We expect the board and players sidebar to appear
        await expect(page.locator('text=SUA VEZ: Selecione uma Letra').or(page.locator('text=Aguarde sua vez...'))).toBeVisible({ timeout: 10000 });
        await expect(guestPage.locator('text=SUA VEZ: Selecione uma Letra').or(guestPage.locator('text=Aguarde sua vez...'))).toBeVisible({ timeout: 10000 });

        // Ensure bot was generated (since we only have 2 players, 1 bot should be added)
        await expect(page.locator('text=Robô 1')).toBeVisible();
    });
});
